<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>ScanSpy</RootNamespace>
    <AssemblyName>ScanSpy</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ScottPlot.WinForms" Version="5.0.54" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bridge\Helios.Client\Helios.Client.csproj" />
  </ItemGroup>

</Project>
