<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>Helios.Bridge.Contracts</RootNamespace>
    <AssemblyName>Helios.Bridge.Contracts</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.28.3" />
    <PackageReference Include="Grpc.Core.Api" Version="2.63.0" />
    <PackageReference Include="Grpc.Tools" Version="2.65.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\*.proto" ProtoRoot="Protos" GrpcServices="Both" />
  </ItemGroup>

</Project>
